_name_: cami
fasta_path: '/home/nmb127/code/data/contigs_2kbp.fna.gz'
fasta_taxonomy: '/home/nmb127/code/data/gt_tax_urog.csv'
dataset_name: cami
tokenizer_name: null
cache_dir: null
max_length: 1024
add_eos: True
batch_size: 8  # per GPU
batch_size_eval: ${eval:${.batch_size} * 2}
num_workers: 4  # For preprocessing only
shuffle: True
rc_aug: True
pin_memory: True
__train_len: ${div_up:1_000_000_000, ${.max_length}}
__l_max: ${.max_length}